### Consider the below code to answer further questions:

In [1]:
import numpy as np

list_ = ['1','2','3','4','5']

array_list = np.array(object = list_)

In [2]:
# Viewing array_list
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

### Queston 1 : Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables

### Answer :
### Yes, there is a difference in the data type of the list_ and array_list variables.
#### The list_ variable is a Python list of strings, whereas array_list is a NumPy array of strings. Although they both contain the same string values, they have different data types because they are different types of objects.
#### Code to check type below :

In [4]:
# Checking type of list_ and array_list
print('Type of list_ is :',type(list_))
print('Type of array_list is :',type(array_list))

Type of list_ is : <class 'list'>
Type of array_list is : <class 'numpy.ndarray'>


#### Question 2: Write a code to print the data type of each and every element of both the variables list_ and array_list.

### Answer:

In [5]:
# Printing data types of each and every element in list_:
for i in list_:
    print(f'Element value : {i}, datatype = {type(i)}')

Element value : 1, datatype = <class 'str'>
Element value : 2, datatype = <class 'str'>
Element value : 3, datatype = <class 'str'>
Element value : 4, datatype = <class 'str'>
Element value : 5, datatype = <class 'str'>


In [6]:
# Printing data types of each and every element in array_list
for i in array_list:
    print(f'Element value : {i}, datatype = {type(i)}')

Element value : 1, datatype = <class 'numpy.str_'>
Element value : 2, datatype = <class 'numpy.str_'>
Element value : 3, datatype = <class 'numpy.str_'>
Element value : 4, datatype = <class 'numpy.str_'>
Element value : 5, datatype = <class 'numpy.str_'>


#### 

#### Question 3: Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)
# Viewing array_list
array_list
array([1, 2, 3, 4, 5])

#### Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_and array_list.

### 

### Answer:

Yes There will be difference in datatypes of elements present in both lists.
List elements will have data type string and array_list will have datatype numpy integer
Below is code for showing same

In [8]:
# Printing data types of each and every element in list_:
for i in list_:
    print(f'Element value : {i}, datatype = {type(i)}')

Element value : 1, datatype = <class 'str'>
Element value : 2, datatype = <class 'str'>
Element value : 3, datatype = <class 'str'>
Element value : 4, datatype = <class 'str'>
Element value : 5, datatype = <class 'str'>


In [9]:
# Printing data types of each and every element in modified array_list
for i in array_list:
    print(f'Element value : {i}, datatype = {type(i)}')

Element value : 1, datatype = <class 'numpy.str_'>
Element value : 2, datatype = <class 'numpy.str_'>
Element value : 3, datatype = <class 'numpy.str_'>
Element value : 4, datatype = <class 'numpy.str_'>
Element value : 5, datatype = <class 'numpy.str_'>


# Consider the below code to answer further questions:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)
# Viewing num_array
num_array
array([[1, 2, 3],
       [4, 5, 6]])

# Question 4: Write a code to find the following characteristics of variable, num_array:

1. shape
2. size

# Answer

In [16]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

#Viewing num_array
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
# Showing num_array shape
np.shape(num_array)

(2, 3)

In [18]:
#Showing size
np.size(num_array)

6

# Question 5: Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

# Answer: 

In [19]:
## Using np.zeros to create a 3X3 matrix containing zeros
arr5 = np.zeros((3,3))
arr5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# Verifying Matrix size and shape
print(f'Size of arr5 is {arr5.size}')
print(f'Shape of arr5 is {arr5.shape}')

Size of arr5 is 9
Shape of arr5 is (3, 3)


# 

# Question 6: 
Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

Answer:

In [22]:
# Creating identity matrix using np.eye
arr6 = np.eye(5)
arr6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])